framework:
  secret: '%env(APP_SECRET)%'
  csrf_protection: true
  http_method_override: true
  handle_all_throwables: true
  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
  assets: ~
  translator:
    default_path: '%kernel.project_dir%/translations'
    fallbacks: ['ru']
  router:
    utf8: true