liip_imagine:
  driver: gd
  resolvers:
    default:
      web_path: ~
  filter_sets:
    cache: ~
    passport_thumb:
      quality: 80
      filters:
        thumbnail: { size: [400, 400], mode: inset }