vich_uploader:
  db_driver: orm
  storage: file_system
  mappings:
    passport_images:
      uri_prefix: /private
      upload_destination: '%kernel.project_dir%/var/private_uploads/passports'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_remove: true
      delete_on_update: true